---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qhch72hhp8lo/public_html
    - npm install
    - npm run generate
    - /bin/cp -R .output/public/* $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/ 2>/dev/null || true
    - /bin/cp .env $DEPLOYPATH/ 2>/dev/null || true